// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	Course struct {
		ID, Title, Description, AvailabilityType, AvailableFrom, AvailableTo, TimeLimitMinutes, CreatedAt, StatusID string
	}
	Exam struct {
		ID, CourseID, StudentID, Answers, TotalQuestions, CorrectAnswers, Status, FinalScore, FinishedAt, CreatedAt, QuestionIDs string

		Course, Student string
	}
	Question struct {
		ID, CourseID, PhotoFileID, QuestionText, Options, QuestionType, CreatedAt string

		Course, PhotoFile string
	}
	Student struct {
		ID, Login, PasswordHash, FirstName, LastName, Email, CreatedAt, StatusID string
	}
	VfsFile struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}
	VfsFolder struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	Course: struct {
		ID, Title, Description, AvailabilityType, AvailableFrom, AvailableTo, TimeLimitMinutes, CreatedAt, StatusID string
	}{
		ID:               "courseId",
		Title:            "title",
		Description:      "description",
		AvailabilityType: "availabilityType",
		AvailableFrom:    "availableFrom",
		AvailableTo:      "availableTo",
		TimeLimitMinutes: "timeLimitMinutes",
		CreatedAt:        "createdAt",
		StatusID:         "statusId",
	},
	Exam: struct {
		ID, CourseID, StudentID, Answers, TotalQuestions, CorrectAnswers, Status, FinalScore, FinishedAt, CreatedAt, QuestionIDs string

		Course, Student string
	}{
		ID:             "examId",
		CourseID:       "courseId",
		StudentID:      "studentId",
		Answers:        "answers",
		TotalQuestions: "totalQuestions",
		CorrectAnswers: "correctAnswers",
		Status:         "status",
		FinalScore:     "finalScore",
		FinishedAt:     "finishedAt",
		CreatedAt:      "createdAt",
		QuestionIDs:    "questionIds",

		Course:  "Course",
		Student: "Student",
	},
	Question: struct {
		ID, CourseID, PhotoFileID, QuestionText, Options, QuestionType, CreatedAt string

		Course, PhotoFile string
	}{
		ID:           "questionId",
		CourseID:     "courseId",
		PhotoFileID:  "photoFileId",
		QuestionText: "questionText",
		Options:      "options",
		QuestionType: "questionType",
		CreatedAt:    "createdAt",

		Course:    "Course",
		PhotoFile: "PhotoFile",
	},
	Student: struct {
		ID, Login, PasswordHash, FirstName, LastName, Email, CreatedAt, StatusID string
	}{
		ID:           "studentId",
		Login:        "login",
		PasswordHash: "passwordHash",
		FirstName:    "firstName",
		LastName:     "lastName",
		Email:        "email",
		CreatedAt:    "createdAt",
		StatusID:     "statusId",
	},
	VfsFile: struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}{
		ID:         "fileId",
		FolderID:   "folderId",
		Title:      "title",
		Path:       "path",
		Params:     "params",
		IsFavorite: "isFavorite",
		MimeType:   "mimeType",
		FileSize:   "fileSize",
		FileExists: "fileExists",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Folder: "Folder",
	},
	VfsFolder: struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}{
		ID:             "folderId",
		ParentFolderID: "parentFolderId",
		Title:          "title",
		IsFavorite:     "isFavorite",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",

		ParentFolder: "ParentFolder",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	Course struct {
		Name, Alias string
	}
	Exam struct {
		Name, Alias string
	}
	Question struct {
		Name, Alias string
	}
	Student struct {
		Name, Alias string
	}
	VfsFile struct {
		Name, Alias string
	}
	VfsFolder struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	Course: struct {
		Name, Alias string
	}{
		Name:  "courses",
		Alias: "t",
	},
	Exam: struct {
		Name, Alias string
	}{
		Name:  "exams",
		Alias: "t",
	},
	Question: struct {
		Name, Alias string
	}{
		Name:  "questions",
		Alias: "t",
	},
	Student: struct {
		Name, Alias string
	}{
		Name:  "students",
		Alias: "t",
	},
	VfsFile: struct {
		Name, Alias string
	}{
		Name:  "vfsFiles",
		Alias: "t",
	},
	VfsFolder: struct {
		Name, Alias string
	}{
		Name:  "vfsFolders",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type Course struct {
	tableName struct{} `pg:"courses,alias:t,discard_unknown_columns"`

	ID               int        `pg:"courseId,pk"`
	Title            string     `pg:"title,use_zero"`
	Description      string     `pg:"description,use_zero"`
	AvailabilityType string     `pg:"availabilityType,use_zero"`
	AvailableFrom    *time.Time `pg:"availableFrom"`
	AvailableTo      *time.Time `pg:"availableTo"`
	TimeLimitMinutes *int       `pg:"timeLimitMinutes"`
	CreatedAt        time.Time  `pg:"createdAt,use_zero"`
	StatusID         int        `pg:"statusId,use_zero"`
}

type Exam struct {
	tableName struct{} `pg:"exams,alias:t,discard_unknown_columns"`

	ID             int         `pg:"examId,pk"`
	CourseID       int         `pg:"courseId,use_zero"`
	StudentID      int         `pg:"studentId,use_zero"`
	Answers        ExamAnswers `pg:"answers,use_zero"`
	TotalQuestions *int        `pg:"totalQuestions"`
	CorrectAnswers *int        `pg:"correctAnswers"`
	Status         string      `pg:"status,use_zero"`
	FinalScore     *float64    `pg:"finalScore"`
	FinishedAt     *time.Time  `pg:"finishedAt"`
	CreatedAt      time.Time   `pg:"createdAt,use_zero"`
	QuestionIDs    []int       `pg:"questionIds,array,use_zero"`

	Course  *Course  `pg:"fk:courseId,rel:has-one"`
	Student *Student `pg:"fk:studentId,rel:has-one"`
}

type Question struct {
	tableName struct{} `pg:"questions,alias:t,discard_unknown_columns"`

	ID           int             `pg:"questionId,pk"`
	CourseID     int             `pg:"courseId,use_zero"`
	PhotoFileID  *int            `pg:"photoFileId"`
	QuestionText string          `pg:"questionText,use_zero"`
	Options      QuestionOptions `pg:"options,use_zero"`
	QuestionType string          `pg:"questionType,use_zero"`
	CreatedAt    time.Time       `pg:"createdAt,use_zero"`

	Course    *Course  `pg:"fk:courseId,rel:has-one"`
	PhotoFile *VfsFile `pg:"fk:photoFileId,rel:has-one"`
}

type Student struct {
	tableName struct{} `pg:"students,alias:t,discard_unknown_columns"`

	ID           int       `pg:"studentId,pk"`
	Login        string    `pg:"login,use_zero"`
	PasswordHash string    `pg:"passwordHash,use_zero"`
	FirstName    string    `pg:"firstName,use_zero"`
	LastName     string    `pg:"lastName,use_zero"`
	Email        string    `pg:"email,use_zero"`
	CreatedAt    time.Time `pg:"createdAt,use_zero"`
	StatusID     int       `pg:"statusId,use_zero"`
}

type VfsFile struct {
	tableName struct{} `pg:"vfsFiles,alias:t,discard_unknown_columns"`

	ID         int       `pg:"fileId,pk"`
	FolderID   int       `pg:"folderId,use_zero"`
	Title      string    `pg:"title,use_zero"`
	Path       string    `pg:"path,use_zero"`
	Params     *string   `pg:"params"`
	IsFavorite *bool     `pg:"isFavorite"`
	MimeType   string    `pg:"mimeType,use_zero"`
	FileSize   *int      `pg:"fileSize"`
	FileExists bool      `pg:"fileExists,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`

	Folder *VfsFolder `pg:"fk:folderId,rel:has-one"`
}

type VfsFolder struct {
	tableName struct{} `pg:"vfsFolders,alias:t,discard_unknown_columns"`

	ID             int       `pg:"folderId,pk"`
	ParentFolderID *int      `pg:"parentFolderId"`
	Title          string    `pg:"title,use_zero"`
	IsFavorite     *bool     `pg:"isFavorite"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`

	ParentFolder *VfsFolder `pg:"fk:parentFolderId,rel:has-one"`
}
