// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type UserSearch struct {
	search

	ID                 *int
	CreatedAt          *time.Time
	Login              *string
	Password           *string
	AuthKey            *string
	LastActivityAt     *time.Time
	StatusID           *int
	IDs                []int
	NotID              *int
	LoginILike         *string
	PasswordILike      *string
	AuthKeyILike       *string
	LastActivityAtFrom *time.Time
	LastActivityAtTo   *time.Time
}

func (us *UserSearch) Apply(query *orm.Query) *orm.Query {
	if us == nil {
		return query
	}
	if us.ID != nil {
		us.where(query, Tables.User.Alias, Columns.User.ID, us.ID)
	}
	if us.CreatedAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.CreatedAt, us.CreatedAt)
	}
	if us.Login != nil {
		us.where(query, Tables.User.Alias, Columns.User.Login, us.Login)
	}
	if us.Password != nil {
		us.where(query, Tables.User.Alias, Columns.User.Password, us.Password)
	}
	if us.AuthKey != nil {
		us.where(query, Tables.User.Alias, Columns.User.AuthKey, us.AuthKey)
	}
	if us.LastActivityAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.LastActivityAt, us.LastActivityAt)
	}
	if us.StatusID != nil {
		us.where(query, Tables.User.Alias, Columns.User.StatusID, us.StatusID)
	}
	if len(us.IDs) > 0 {
		Filter{Columns.User.ID, us.IDs, SearchTypeArray, false}.Apply(query)
	}
	if us.NotID != nil {
		Filter{Columns.User.ID, *us.NotID, SearchTypeEquals, true}.Apply(query)
	}
	if us.LoginILike != nil {
		Filter{Columns.User.Login, *us.LoginILike, SearchTypeILike, false}.Apply(query)
	}
	if us.PasswordILike != nil {
		Filter{Columns.User.Password, *us.PasswordILike, SearchTypeILike, false}.Apply(query)
	}
	if us.AuthKeyILike != nil {
		Filter{Columns.User.AuthKey, *us.AuthKeyILike, SearchTypeILike, false}.Apply(query)
	}
	if us.LastActivityAtFrom != nil {
		Filter{Columns.User.LastActivityAt, *us.LastActivityAtFrom, SearchTypeGE, false}.Apply(query)
	}
	if us.LastActivityAtTo != nil {
		Filter{Columns.User.LastActivityAt, *us.LastActivityAtTo, SearchTypeLE, false}.Apply(query)
	}

	us.apply(query)

	return query
}

func (us *UserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if us == nil {
			return query, nil
		}
		return us.Apply(query), nil
	}
}

type CourseSearch struct {
	search

	ID                    *int
	Title                 *string
	Description           *string
	AvailabilityType      *string
	AvailableFrom         *time.Time
	AvailableTo           *time.Time
	TimeLimitMinutes      *int
	CreatedAt             *time.Time
	StatusID              *int
	IDs                   []int
	AvailableToFrom       *time.Time
	AvailableFromTo       *time.Time
	TitleILike            *string
	DescriptionILike      *string
	AvailabilityTypeILike *string
}

func (cs *CourseSearch) Apply(query *orm.Query) *orm.Query {
	if cs == nil {
		return query
	}
	if cs.ID != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.ID, cs.ID)
	}
	if cs.Title != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.Title, cs.Title)
	}
	if cs.Description != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.Description, cs.Description)
	}
	if cs.AvailabilityType != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.AvailabilityType, cs.AvailabilityType)
	}
	if cs.AvailableFrom != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.AvailableFrom, cs.AvailableFrom)
	}
	if cs.AvailableTo != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.AvailableTo, cs.AvailableTo)
	}
	if cs.TimeLimitMinutes != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.TimeLimitMinutes, cs.TimeLimitMinutes)
	}
	if cs.CreatedAt != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.CreatedAt, cs.CreatedAt)
	}
	if cs.StatusID != nil {
		cs.where(query, Tables.Course.Alias, Columns.Course.StatusID, cs.StatusID)
	}
	if len(cs.IDs) > 0 {
		Filter{Columns.Course.ID, cs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if cs.AvailableToFrom != nil {
		Filter{Columns.Course.AvailableTo, *cs.AvailableToFrom, SearchTypeGE, false}.Apply(query)
	}
	if cs.AvailableFromTo != nil {
		Filter{Columns.Course.AvailableFrom, *cs.AvailableFromTo, SearchTypeLE, false}.Apply(query)
	}
	if cs.TitleILike != nil {
		Filter{Columns.Course.Title, *cs.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.DescriptionILike != nil {
		Filter{Columns.Course.Description, *cs.DescriptionILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.AvailabilityTypeILike != nil {
		Filter{Columns.Course.AvailabilityType, *cs.AvailabilityTypeILike, SearchTypeILike, false}.Apply(query)
	}

	cs.apply(query)

	return query
}

func (cs *CourseSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if cs == nil {
			return query, nil
		}
		return cs.Apply(query), nil
	}
}

type ExamSearch struct {
	search

	ID             *int
	CourseID       *int
	StudentID      *int
	TotalQuestions *int
	CorrectAnswers *int
	Status         *string
	FinalScore     *float64
	FinishedAt     *time.Time
	CreatedAt      *time.Time
	IDs            []int
	StatusILike    *string
}

func (es *ExamSearch) Apply(query *orm.Query) *orm.Query {
	if es == nil {
		return query
	}
	if es.ID != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.ID, es.ID)
	}
	if es.CourseID != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.CourseID, es.CourseID)
	}
	if es.StudentID != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.StudentID, es.StudentID)
	}
	if es.TotalQuestions != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.TotalQuestions, es.TotalQuestions)
	}
	if es.CorrectAnswers != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.CorrectAnswers, es.CorrectAnswers)
	}
	if es.Status != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.Status, es.Status)
	}
	if es.FinalScore != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.FinalScore, es.FinalScore)
	}
	if es.FinishedAt != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.FinishedAt, es.FinishedAt)
	}
	if es.CreatedAt != nil {
		es.where(query, Tables.Exam.Alias, Columns.Exam.CreatedAt, es.CreatedAt)
	}
	if len(es.IDs) > 0 {
		Filter{Columns.Exam.ID, es.IDs, SearchTypeArray, false}.Apply(query)
	}
	if es.StatusILike != nil {
		Filter{Columns.Exam.Status, *es.StatusILike, SearchTypeILike, false}.Apply(query)
	}

	es.apply(query)

	return query
}

func (es *ExamSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if es == nil {
			return query, nil
		}
		return es.Apply(query), nil
	}
}

type QuestionSearch struct {
	search

	ID                *int
	CourseID          *int
	PhotoFileID       *int
	QuestionText      *string
	QuestionType      *string
	CreatedAt         *time.Time
	IDs               []int
	QuestionTextILike *string
	QuestionTypeILike *string
}

func (qs *QuestionSearch) Apply(query *orm.Query) *orm.Query {
	if qs == nil {
		return query
	}
	if qs.ID != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.ID, qs.ID)
	}
	if qs.CourseID != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.CourseID, qs.CourseID)
	}
	if qs.PhotoFileID != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.PhotoFileID, qs.PhotoFileID)
	}
	if qs.QuestionText != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.QuestionText, qs.QuestionText)
	}
	if qs.QuestionType != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.QuestionType, qs.QuestionType)
	}
	if qs.CreatedAt != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.CreatedAt, qs.CreatedAt)
	}
	if len(qs.IDs) > 0 {
		Filter{Columns.Question.ID, qs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if qs.QuestionTextILike != nil {
		Filter{Columns.Question.QuestionText, *qs.QuestionTextILike, SearchTypeILike, false}.Apply(query)
	}
	if qs.QuestionTypeILike != nil {
		Filter{Columns.Question.QuestionType, *qs.QuestionTypeILike, SearchTypeILike, false}.Apply(query)
	}

	qs.apply(query)

	return query
}

func (qs *QuestionSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if qs == nil {
			return query, nil
		}
		return qs.Apply(query), nil
	}
}

type StudentSearch struct {
	search

	ID                *int
	Login             *string
	PasswordHash      *string
	FirstName         *string
	LastName          *string
	Email             *string
	CreatedAt         *time.Time
	StatusID          *int
	IDs               []int
	LoginILike        *string
	PasswordHashILike *string
	FirstNameILike    *string
	LastNameILike     *string
	EmailILike        *string
}

func (ss *StudentSearch) Apply(query *orm.Query) *orm.Query {
	if ss == nil {
		return query
	}
	if ss.ID != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.ID, ss.ID)
	}
	if ss.Login != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.Login, ss.Login)
	}
	if ss.PasswordHash != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.PasswordHash, ss.PasswordHash)
	}
	if ss.FirstName != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.FirstName, ss.FirstName)
	}
	if ss.LastName != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.LastName, ss.LastName)
	}
	if ss.Email != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.Email, ss.Email)
	}
	if ss.CreatedAt != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.CreatedAt, ss.CreatedAt)
	}
	if ss.StatusID != nil {
		ss.where(query, Tables.Student.Alias, Columns.Student.StatusID, ss.StatusID)
	}
	if len(ss.IDs) > 0 {
		Filter{Columns.Student.ID, ss.IDs, SearchTypeArray, false}.Apply(query)
	}
	if ss.LoginILike != nil {
		Filter{Columns.Student.Login, *ss.LoginILike, SearchTypeILike, false}.Apply(query)
	}
	if ss.PasswordHashILike != nil {
		Filter{Columns.Student.PasswordHash, *ss.PasswordHashILike, SearchTypeILike, false}.Apply(query)
	}
	if ss.FirstNameILike != nil {
		Filter{Columns.Student.FirstName, *ss.FirstNameILike, SearchTypeILike, false}.Apply(query)
	}
	if ss.LastNameILike != nil {
		Filter{Columns.Student.LastName, *ss.LastNameILike, SearchTypeILike, false}.Apply(query)
	}
	if ss.EmailILike != nil {
		Filter{Columns.Student.Email, *ss.EmailILike, SearchTypeILike, false}.Apply(query)
	}

	ss.apply(query)

	return query
}

func (ss *StudentSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if ss == nil {
			return query, nil
		}
		return ss.Apply(query), nil
	}
}

type VfsFileSearch struct {
	search

	ID            *int
	FolderID      *int
	Title         *string
	Path          *string
	Params        *string
	IsFavorite    *bool
	MimeType      *string
	FileSize      *int
	FileExists    *bool
	CreatedAt     *time.Time
	StatusID      *int
	IDs           []int
	TitleILike    *string
	PathILike     *string
	ParamsILike   *string
	MimeTypeILike *string
}

func (vfs *VfsFileSearch) Apply(query *orm.Query) *orm.Query {
	if vfs == nil {
		return query
	}
	if vfs.ID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.ID, vfs.ID)
	}
	if vfs.FolderID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FolderID, vfs.FolderID)
	}
	if vfs.Title != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Title, vfs.Title)
	}
	if vfs.Path != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Path, vfs.Path)
	}
	if vfs.Params != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Params, vfs.Params)
	}
	if vfs.IsFavorite != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.IsFavorite, vfs.IsFavorite)
	}
	if vfs.MimeType != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.MimeType, vfs.MimeType)
	}
	if vfs.FileSize != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FileSize, vfs.FileSize)
	}
	if vfs.FileExists != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FileExists, vfs.FileExists)
	}
	if vfs.CreatedAt != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.CreatedAt, vfs.CreatedAt)
	}
	if vfs.StatusID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.StatusID, vfs.StatusID)
	}
	if len(vfs.IDs) > 0 {
		Filter{Columns.VfsFile.ID, vfs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if vfs.TitleILike != nil {
		Filter{Columns.VfsFile.Title, *vfs.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.PathILike != nil {
		Filter{Columns.VfsFile.Path, *vfs.PathILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.ParamsILike != nil {
		Filter{Columns.VfsFile.Params, *vfs.ParamsILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.MimeTypeILike != nil {
		Filter{Columns.VfsFile.MimeType, *vfs.MimeTypeILike, SearchTypeILike, false}.Apply(query)
	}

	vfs.apply(query)

	return query
}

func (vfs *VfsFileSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if vfs == nil {
			return query, nil
		}
		return vfs.Apply(query), nil
	}
}

type VfsFolderSearch struct {
	search

	ID             *int
	ParentFolderID *int
	Title          *string
	IsFavorite     *bool
	CreatedAt      *time.Time
	StatusID       *int
	IDs            []int
	TitleILike     *string
}

func (vfs *VfsFolderSearch) Apply(query *orm.Query) *orm.Query {
	if vfs == nil {
		return query
	}
	if vfs.ID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.ID, vfs.ID)
	}
	if vfs.ParentFolderID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.ParentFolderID, vfs.ParentFolderID)
	}
	if vfs.Title != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.Title, vfs.Title)
	}
	if vfs.IsFavorite != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.IsFavorite, vfs.IsFavorite)
	}
	if vfs.CreatedAt != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.CreatedAt, vfs.CreatedAt)
	}
	if vfs.StatusID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.StatusID, vfs.StatusID)
	}
	if len(vfs.IDs) > 0 {
		Filter{Columns.VfsFolder.ID, vfs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if vfs.TitleILike != nil {
		Filter{Columns.VfsFolder.Title, *vfs.TitleILike, SearchTypeILike, false}.Apply(query)
	}

	vfs.apply(query)

	return query
}

func (vfs *VfsFolderSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if vfs == nil {
			return query, nil
		}
		return vfs.Apply(query), nil
	}
}
