// Code generated by colgen v0.1.3; DO NOT EDIT.
package coursepass

import (
	"courses/pkg/db"
)

func newCourseSummaries(in []db.Course) []CourseSummary { return Map(in, newCourseSummary) }

func newExamSummaries(in []db.Exam) []ExamSummary { return Map(in, newExamSummary) }

func newQuestionOptions(in []db.QuestionOption) []QuestionOption { return Map(in, newQuestionOption) }
