// Code generated by colgen v0.1.3; DO NOT EDIT.
package coursepass

type ExamAnswers []ExamAnswer

func (ll ExamAnswers) IndexByQuestionID() map[int]ExamAnswer {
	r := make(map[int]ExamAnswer, len(ll))
	for i := range ll {
		r[ll[i].QuestionID] = ll[i]
	}
	return r
}

type Questions []Question

func (ll Questions) QuestionIDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].QuestionID
	}
	return r
}

func (ll Questions) IndexByQuestionID() map[int]Question {
	r := make(map[int]Question, len(ll))
	for i := range ll {
		r[ll[i].QuestionID] = ll[i]
	}
	return r
}

type QuestionOptions []QuestionOption

func (ll QuestionOptions) OptionIDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].OptionID
	}
	return r
}

func (ll QuestionOptions) IndexByOptionID() map[int]QuestionOption {
	r := make(map[int]QuestionOption, len(ll))
	for i := range ll {
		r[ll[i].OptionID] = ll[i]
	}
	return r
}

func (ll QuestionOptions) GroupByIsCorrect() map[bool]QuestionOptions {
	r := make(map[bool]QuestionOptions, len(ll))
	for i := range ll {
		r[ll[i].IsCorrect] = append(r[ll[i].IsCorrect], ll[i])
	}
	return r
}
