// Code generated by colgen v0.1.3; DO NOT EDIT.
package rpc

import (
	"courses/pkg/coursepass"
)

func newCourseSummaries(in []coursepass.Course) []CourseSummary { return Map(in, newCourseSummary) }

func newExamSummaries(in []coursepass.Exam) []ExamSummary { return Map(in, newExamSummary) }

func newFieldErrors(in []coursepass.FieldError) []FieldError { return Map(in, newFieldError) }

func NewQuestionOptions(in []coursepass.QuestionOption) []QuestionOption {
	return Map(in, NewQuestionOption)
}
