// Code generated by colgen v0.1.3; DO NOT EDIT.
package rpc

import (
	"courses/pkg/coursepass"
)

func newCourseSummaries(in []coursepass.CourseSummary) []CourseSummary {
	return Map(in, newCourseSummary)
}

func NewQuestionOptions(in []coursepass.QuestionOption) []QuestionOption {
	return Map(in, NewQuestionOption)
}
