// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	AuthService    struct{ Register, Login string }
	CoursesService struct{ Me, List, ById string }
	ExamService    struct{ Start string }
}{
	AuthService: struct{ Register, Login string }{
		Register: "register",
		Login:    "login",
	},
	CoursesService: struct{ Me, List, ById string }{
		Me:   "me",
		List: "list",
		ById: "byid",
	},
	ExamService: struct{ Start string }{
		Start: "start",
	},
}

func (AuthService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Register": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "RegisterRequest",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
							{
								Name: "email",
								Type: smd.String,
							},
							{
								Name: "firstName",
								Type: smd.String,
							},
							{
								Name: "lastName",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "RegisterResponse",
					Properties: smd.PropertyList{
						{
							Name: "accessToken",
							Type: smd.String,
						},
						{
							Name: "expiresIn",
							Type: smd.Integer,
						},
						{
							Name: "tokenType",
							Type: smd.String,
						},
					},
				},
			},
			"Login": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "LoginRequest",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "LoginResponse",
					Properties: smd.PropertyList{
						{
							Name: "accessToken",
							Type: smd.String,
						},
						{
							Name: "expiresIn",
							Type: smd.Integer,
						},
						{
							Name: "tokenType",
							Type: smd.String,
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s AuthService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.AuthService.Register:
		var args = struct {
			Req RegisterRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Register(ctx, args.Req))

	case RPC.AuthService.Login:
		var args = struct {
			Req LoginRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Login(ctx, args.Req))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (CoursesService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Me": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "MeResponse",
					Properties: smd.PropertyList{
						{
							Name: "studentId",
							Type: smd.Integer,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "email",
							Type: smd.String,
						},
						{
							Name: "firstName",
							Type: smd.String,
						},
						{
							Name: "lastName",
							Type: smd.String,
						},
					},
				},
			},
			"List": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "ListRequest",
						Properties: smd.PropertyList{
							{
								Name: "page",
								Type: smd.Integer,
							},
							{
								Name: "pageSize",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "ListResponse",
					Properties: smd.PropertyList{
						{
							Name: "courses",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/CourseSummary",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"CourseSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "courseId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name:     "timeLimit",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "availableType",
									Type: smd.String,
								},
								{
									Name:     "availableFrom",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "availableTo",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
			},
			"ById": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "ByIdRequest",
						Properties: smd.PropertyList{
							{
								Name: "courseId",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "ByIdResponse",
					Properties: smd.PropertyList{
						{
							Name: "course",
							Ref:  "#/definitions/Course",
							Type: smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"Course": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "courseId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name:     "timeLimit",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "availableType",
									Type: smd.String,
								},
								{
									Name:     "availableFrom",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "availableTo",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s CoursesService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.CoursesService.Me:
		resp.Set(s.Me(ctx))

	case RPC.CoursesService.List:
		var args = struct {
			Req ListRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.List(ctx, args.Req))

	case RPC.CoursesService.ById:
		var args = struct {
			Req ByIdRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ById(ctx, args.Req))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (ExamService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Start": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "req",
						Type:     smd.Object,
						TypeName: "ExamStartRequest",
						Properties: smd.PropertyList{
							{
								Name: "courseId",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "ExamStartResponse",
					Properties: smd.PropertyList{
						{
							Name: "examId",
							Type: smd.Integer,
						},
						{
							Name: "questionIds",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.Integer,
							},
						},
						{
							Name: "startedAt",
							Type: smd.String,
						},
						{
							Name:     "finishedAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s ExamService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.ExamService.Start:
		var args = struct {
			Req ExamStartRequest `json:"req"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"req"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Start(ctx, args.Req))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
