// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	AuthService    struct{ ValidateStudent, RegisterStudent, ValidateStudentLogin, Login string }
	CoursesService struct{ Me, List, ByID string }
	ExamService    struct{ Start, GetQuestion, Answer, Submit, History string }
}{
	AuthService: struct{ ValidateStudent, RegisterStudent, ValidateStudentLogin, Login string }{
		ValidateStudent:      "validatestudent",
		RegisterStudent:      "registerstudent",
		ValidateStudentLogin: "validatestudentlogin",
		Login:                "login",
	},
	CoursesService: struct{ Me, List, ByID string }{
		Me:   "me",
		List: "list",
		ByID: "byid",
	},
	ExamService: struct{ Start, GetQuestion, Answer, Submit, History string }{
		Start:       "start",
		GetQuestion: "getquestion",
		Answer:      "answer",
		Submit:      "submit",
		History:     "history",
	},
}

func (AuthService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"ValidateStudent": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "StudentDraft",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "email",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
							{
								Name: "firstName",
								Type: smd.String,
							},
							{
								Name: "lastName",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]FieldError",
					Items: map[string]string{
						"$ref": "#/definitions/FieldError",
					},
					Definitions: map[string]smd.Definition{
						"FieldError": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "field",
									Type: smd.String,
								},
								{
									Name: "error",
									Type: smd.String,
								},
								{
									Name:     "constraint",
									Optional: true,
									Ref:      "#/definitions/FieldErrorConstraint",
									Type:     smd.Object,
								},
							},
						},
						"FieldErrorConstraint": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "max",
									Type: smd.Integer,
								},
								{
									Name: "min",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "internal error",
				},
			},
			"RegisterStudent": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "StudentDraft",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "email",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
							{
								Name: "firstName",
								Type: smd.String,
							},
							{
								Name: "lastName",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Token",
					Properties: smd.PropertyList{
						{
							Name: "accessToken",
							Type: smd.String,
						},
						{
							Name: "expiresIn",
							Type: smd.Integer,
						},
						{
							Name: "tokenType",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					409: "login or email exists",
					500: "internal error",
				},
			},
			"ValidateStudentLogin": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "StudentLogin",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]FieldError",
					Items: map[string]string{
						"$ref": "#/definitions/FieldError",
					},
					Definitions: map[string]smd.Definition{
						"FieldError": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "field",
									Type: smd.String,
								},
								{
									Name: "error",
									Type: smd.String,
								},
								{
									Name:     "constraint",
									Optional: true,
									Ref:      "#/definitions/FieldErrorConstraint",
									Type:     smd.Object,
								},
							},
						},
						"FieldErrorConstraint": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "max",
									Type: smd.Integer,
								},
								{
									Name: "min",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "internal error",
				},
			},
			"Login": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "StudentLogin",
						Properties: smd.PropertyList{
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "password",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Token",
					Properties: smd.PropertyList{
						{
							Name: "accessToken",
							Type: smd.String,
						},
						{
							Name: "expiresIn",
							Type: smd.Integer,
						},
						{
							Name: "tokenType",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					401: "invalid credentials",
					500: "internal error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s AuthService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.AuthService.ValidateStudent:
		var args = struct {
			In StudentDraft `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ValidateStudent(ctx, args.In))

	case RPC.AuthService.RegisterStudent:
		var args = struct {
			In StudentDraft `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.RegisterStudent(ctx, args.In))

	case RPC.AuthService.ValidateStudentLogin:
		var args = struct {
			In StudentLogin `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ValidateStudentLogin(ctx, args.In))

	case RPC.AuthService.Login:
		var args = struct {
			In StudentLogin `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Login(ctx, args.In))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (CoursesService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Me": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Student",
					Properties: smd.PropertyList{
						{
							Name: "studentId",
							Type: smd.Integer,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "email",
							Type: smd.String,
						},
						{
							Name: "firstName",
							Type: smd.String,
						},
						{
							Name: "lastName",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					401: "invalid token",
					404: "not found",
					500: "internal error",
				},
			},
			"List": {
				Parameters: []smd.JSONSchema{
					{
						Name: "page",
						Type: smd.Integer,
					},
					{
						Name: "pageSize",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]CourseSummary",
					Items: map[string]string{
						"$ref": "#/definitions/CourseSummary",
					},
					Definitions: map[string]smd.Definition{
						"CourseSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "courseId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name:     "timeLimit",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "availableType",
									Type: smd.String,
								},
								{
									Name:     "availableFrom",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "availableTo",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "internal error",
				},
			},
			"ByID": {
				Parameters: []smd.JSONSchema{
					{
						Name: "courseID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Course",
					Properties: smd.PropertyList{
						{
							Name: "courseId",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name:     "timeLimit",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "availableType",
							Type: smd.String,
						},
						{
							Name:     "availableFrom",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name:     "availableTo",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
					500: "internal error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s CoursesService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.CoursesService.Me:
		resp.Set(s.Me(ctx))

	case RPC.CoursesService.List:
		var args = struct {
			Page     int `json:"page"`
			PageSize int `json:"pageSize"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"page", "pageSize"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.List(ctx, args.Page, args.PageSize))

	case RPC.CoursesService.ByID:
		var args = struct {
			CourseID int `json:"courseID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"courseID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ByID(ctx, args.CourseID))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (ExamService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Start": {
				Parameters: []smd.JSONSchema{
					{
						Name: "courseID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "ExamStart",
					Properties: smd.PropertyList{
						{
							Name: "examId",
							Type: smd.Integer,
						},
						{
							Name: "questionIds",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.Integer,
							},
						},
						{
							Name: "startedAt",
							Type: smd.String,
						},
						{
							Name:     "finishedAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					401: "invalid token",
					404: "not found",
					409: "exam conflict",
					500: "internal error",
				},
			},
			"GetQuestion": {
				Parameters: []smd.JSONSchema{
					{
						Name: "examID",
						Type: smd.Integer,
					},
					{
						Name: "questionID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Question",
					Properties: smd.PropertyList{
						{
							Name: "questionId",
							Type: smd.Integer,
						},
						{
							Name: "questionText",
							Type: smd.String,
						},
						{
							Name: "questionType",
							Type: smd.String,
						},
						{
							Name:     "photoUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "options",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/QuestionOption",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"QuestionOption": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "optionId",
									Type: smd.Integer,
								},
								{
									Name: "optionText",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					401: "invalid token",
					404: "not found",
					409: "exam conflict",
					500: "internal error",
				},
			},
			"Answer": {
				Parameters: []smd.JSONSchema{
					{
						Name: "examID",
						Type: smd.Integer,
					},
					{
						Name: "questionID",
						Type: smd.Integer,
					},
					{
						Name:     "optionIDs",
						Type:     smd.Array,
						TypeName: "[]",
						Items: map[string]string{
							"type": smd.Integer,
						},
					},
				},
				Errors: map[int]string{
					401: "invalid token",
					404: "not found",
					409: "exam conflict",
					500: "internal error",
				},
			},
			"Submit": {
				Parameters: []smd.JSONSchema{
					{
						Name: "examID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "ExamResult",
					Properties: smd.PropertyList{
						{
							Name: "examId",
							Type: smd.Integer,
						},
						{
							Name: "status",
							Type: smd.String,
						},
						{
							Name: "finalScore",
							Type: smd.Integer,
						},
						{
							Name: "correctAnswers",
							Type: smd.Integer,
						},
						{
							Name: "totalQuestions",
							Type: smd.Integer,
						},
					},
				},
				Errors: map[int]string{
					401: "invalid token",
					404: "not found",
					409: "exam conflict",
					500: "internal error",
				},
			},
			"History": {
				Parameters: []smd.JSONSchema{
					{
						Name: "page",
						Type: smd.Integer,
					},
					{
						Name: "pageSize",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]ExamSummary",
					Items: map[string]string{
						"$ref": "#/definitions/ExamSummary",
					},
					Definitions: map[string]smd.Definition{
						"ExamSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "examId",
									Type: smd.Integer,
								},
								{
									Name: "courseId",
									Type: smd.Integer,
								},
								{
									Name: "status",
									Type: smd.String,
								},
								{
									Name: "finalScore",
									Type: smd.Integer,
								},
								{
									Name: "finishedAt",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					401: "invalid token",
					500: "internal error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s ExamService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.ExamService.Start:
		var args = struct {
			CourseID int `json:"courseID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"courseID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Start(ctx, args.CourseID))

	case RPC.ExamService.GetQuestion:
		var args = struct {
			ExamID     int `json:"examID"`
			QuestionID int `json:"questionID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"examID", "questionID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetQuestion(ctx, args.ExamID, args.QuestionID))

	case RPC.ExamService.Answer:
		var args = struct {
			ExamID     int   `json:"examID"`
			QuestionID int   `json:"questionID"`
			OptionIDs  []int `json:"optionIDs"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"examID", "questionID", "optionIDs"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Answer(ctx, args.ExamID, args.QuestionID, args.OptionIDs))

	case RPC.ExamService.Submit:
		var args = struct {
			ExamID int `json:"examID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"examID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Submit(ctx, args.ExamID))

	case RPC.ExamService.History:
		var args = struct {
			Page     int `json:"page"`
			PageSize int `json:"pageSize"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"page", "pageSize"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.History(ctx, args.Page, args.PageSize))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
