-- =============================================================================
-- Diagram Name: apisrv
-- Created on: 23.03.2026 20:00:16
-- Diagram Version: 
-- =============================================================================

CREATE TABLE "statuses" (
	"statusId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"alias" varchar(64) NOT NULL,
	CONSTRAINT "statuses_pkey" PRIMARY KEY("statusId"),
	CONSTRAINT "statuses_alias_key" UNIQUE("alias")
);

CREATE TABLE "users" (
	"userId" SERIAL NOT NULL,
	"login" varchar(64) NOT NULL,
	"password" varchar(64) NOT NULL,
	"authKey" varchar(32),
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"lastActivityAt" timestamp with time zone,
	"statusId" int4 NOT NULL,
	CONSTRAINT "users_pkey" PRIMARY KEY("userId")
);

CREATE INDEX "IX_FK_users_statusId_users" ON "users" USING BTREE (
	"statusId"
);


CREATE TABLE "vfsFiles" (
	"fileId" SERIAL NOT NULL,
	"folderId" int4 NOT NULL,
	"title" varchar(255) NOT NULL,
	"path" varchar(255) NOT NULL,
	"params" text,
	"isFavorite" bool DEFAULT false,
	"mimeType" varchar(255) NOT NULL,
	"fileSize" int4 DEFAULT 0,
	"fileExists" bool NOT NULL DEFAULT true,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	CONSTRAINT "vfsFiles_pkey" PRIMARY KEY("fileId")
);

CREATE INDEX "IX_FK_vfsFiles_folderId_vfsFiles" ON "vfsFiles" USING BTREE (
	"folderId"
);


CREATE INDEX "IX_FK_vfsFiles_statusId_vfsFiles" ON "vfsFiles" USING BTREE (
	"statusId"
);


CREATE TABLE "vfsFolders" (
	"folderId" SERIAL NOT NULL,
	"parentFolderId" int4,
	"title" varchar(255) NOT NULL,
	"isFavorite" bool DEFAULT false,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	CONSTRAINT "vfsFolders_pkey" PRIMARY KEY("folderId")
);

CREATE INDEX "IX_FK_vfsFolders_folderId_vfsFolders" ON "vfsFolders" USING BTREE (
	"parentFolderId"
);


CREATE INDEX "IX_FK_vfsFolders_statusId_vfsFolders" ON "vfsFolders" USING BTREE (
	"statusId"
);


CREATE TABLE "vfsHashes" (
	"hash" varchar(40) NOT NULL,
	"namespace" varchar(32) NOT NULL,
	"extension" varchar(4) NOT NULL,
	"fileSize" int4 NOT NULL DEFAULT 0,
	"width" int4 NOT NULL DEFAULT 0,
	"height" int4 NOT NULL DEFAULT 0,
	"blurhash" text,
	"error" text,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"indexedAt" timestamp with time zone,
	CONSTRAINT "vfsHashes_pkey" PRIMARY KEY("hash","namespace")
);

CREATE INDEX "IX_vfsHashes_indexedAt" ON "vfsHashes" USING BTREE (
	"indexedAt"
);


CREATE TABLE "students" (
	"studentId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"login" varchar(255) NOT NULL,
	"passwordHash" varchar(255) NOT NULL,
	"firstName" varchar(255) NOT NULL,
	"lastName" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	PRIMARY KEY("studentId"),
	CONSTRAINT "uq_students_email" UNIQUE("email"),
	CONSTRAINT "uq_students_login" UNIQUE("login")
);

CREATE TABLE "questions" (
	"questionId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"courseId" int4 NOT NULL,
	"photoFileId" int4,
	"questionText" text NOT NULL,
	"options" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"questionType" varchar(255) NOT NULL DEFAULT 'single_choice',
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	PRIMARY KEY("questionId"),
	CONSTRAINT "chk_questions_type" CHECK("questionType" in ('single_choice', 'multiple_choice'))
);

CREATE TABLE "courses" (
	"courseId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"availabilityType" varchar(255) NOT NULL DEFAULT 'always',
	"availableFrom" timestamp with time zone,
	"availableTo" timestamp with time zone,
	"timeLimitMinutes" int4,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	PRIMARY KEY("courseId"),
	CONSTRAINT "chk_courses_availability_type" CHECK("availabilityType" in ('day', 'week', 'month', 'always'))
);

CREATE TABLE "exams" (
	"examId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"courseId" int4 NOT NULL,
	"studentId" int4 NOT NULL,
	"answers" jsonb NOT NULL DEFAULT '[]'::jsonb,
	"questionIds" int4[],
	"totalQuestions" int4,
	"correctAnswers" int4,
	"status" varchar(255) NOT NULL DEFAULT 'in_progress',
	"finalScore" numeric(5,2),
	"finishedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	PRIMARY KEY("examId"),
	CONSTRAINT "chk_exams_status" CHECK("status" in ('in_progress', 'passed', 'failed'))
);


ALTER TABLE "users" ADD CONSTRAINT "FK_users_statusId" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_folderId_fkey" FOREIGN KEY ("folderId")
	REFERENCES "vfsFolders"("folderId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_statusId_fkey" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_parentFolderId_fkey" FOREIGN KEY ("parentFolderId")
	REFERENCES "vfsFolders"("folderId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_statusId_fkey" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "students" ADD CONSTRAINT "Ref_students_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "questions" ADD CONSTRAINT "Ref_questions_to_courses" FOREIGN KEY ("courseId")
	REFERENCES "courses"("courseId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "questions" ADD CONSTRAINT "Ref_questions_to_vfsFiles" FOREIGN KEY ("photoFileId")
	REFERENCES "vfsFiles"("fileId")
	MATCH SIMPLE
	ON DELETE SET NULL
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "courses" ADD CONSTRAINT "Ref_courses_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "exams" ADD CONSTRAINT "Ref_exams_to_courses" FOREIGN KEY ("courseId")
	REFERENCES "courses"("courseId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "exams" ADD CONSTRAINT "Ref_exams_to_students" FOREIGN KEY ("studentId")
	REFERENCES "students"("studentId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;


