CREATE TABLE "statuses" (
                            "statusId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "title" varchar(255) NOT NULL,
                            "alias" varchar(64) NOT NULL,
                            CONSTRAINT "statuses_pkey" PRIMARY KEY("statusId"),
                            CONSTRAINT "statuses_alias_key" UNIQUE("alias")
);

CREATE TABLE "users" (
                         "userId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         "login" varchar(64) NOT NULL,
                         "password" varchar(64) NOT NULL,
                         "authKey" varchar(32),
                         "createdAt" timestamptz NOT NULL DEFAULT now(),
                         "lastActivityAt" timestamptz,
                         "statusId" integer NOT NULL,
                         CONSTRAINT "users_pkey" PRIMARY KEY("userId")
);

CREATE TABLE "vfsFiles" (
                            "fileId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "folderId" integer NOT NULL,
                            "title" varchar(255) NOT NULL,
                            "path" varchar(255) NOT NULL,
                            "params" text,
                            "isFavorite" boolean DEFAULT false,
                            "mimeType" varchar(255) NOT NULL,
                            "fileSize" integer DEFAULT 0,
                            "fileExists" boolean NOT NULL DEFAULT true,
                            "createdAt" timestamp NOT NULL DEFAULT now(),
                            "statusId" integer NOT NULL,
                            CONSTRAINT "vfsFiles_pkey" PRIMARY KEY("fileId")
);

CREATE TABLE "vfsFolders" (
                              "folderId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              "parentFolderId" integer,
                              "title" varchar(255) NOT NULL,
                              "isFavorite" boolean DEFAULT false,
                              "createdAt" timestamp NOT NULL DEFAULT now(),
                              "statusId" integer NOT NULL,
                              CONSTRAINT "vfsFolders_pkey" PRIMARY KEY("folderId")
);

CREATE TABLE "vfsHashes" (
                             "hash" varchar(40) NOT NULL,
                             "namespace" varchar(32) NOT NULL,
                             "extension" varchar(4) NOT NULL,
                             "fileSize" integer NOT NULL DEFAULT 0,
                             "width" integer NOT NULL DEFAULT 0,
                             "height" integer NOT NULL DEFAULT 0,
                             "blurhash" text,
                             "error" text,
                             "createdAt" timestamptz NOT NULL DEFAULT now(),
                             "indexedAt" timestamptz,
                             CONSTRAINT "vfsHashes_pkey" PRIMARY KEY("hash", "namespace")
);

CREATE TABLE "students" (
                            "studentId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "login" varchar(255) NOT NULL,
                            "passwordHash" varchar(255) NOT NULL,
                            "firstName" varchar(255) NOT NULL,
                            "lastName" varchar(255) NOT NULL,
                            "email" varchar(255) NOT NULL,
                            "createdAt" timestamptz NOT NULL DEFAULT now(),
                            "statusId" integer NOT NULL,
                            CONSTRAINT "pk_students" PRIMARY KEY("studentId"),
                            CONSTRAINT "uq_students_email" UNIQUE("email"),
                            CONSTRAINT "uq_students_login" UNIQUE("login")
);

CREATE TABLE "questions" (
                             "questionId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             "courseId" integer NOT NULL,
                             "photoFileId" integer,
                             "questionText" text NOT NULL,
                             "options" jsonb NOT NULL DEFAULT '[]'::jsonb,
                             "questionType" varchar(255) NOT NULL DEFAULT 'single_choice',
                             "createdAt" timestamptz NOT NULL DEFAULT now(),
                             CONSTRAINT "pk_questions" PRIMARY KEY("questionId"),
                             CONSTRAINT "chk_questions_type" CHECK("questionType" in ('single_choice', 'multiple_choice'))
);

CREATE TABLE "courses" (
                           "courseId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "title" varchar(255) NOT NULL,
                           "description" text NOT NULL,
                           "availabilityType" varchar(255) NOT NULL DEFAULT 'always',
                           "availableFrom" timestamptz,
                           "availableTo" timestamptz,
                           "timeLimitMinutes" integer,
                           "createdAt" timestamptz NOT NULL DEFAULT now(),
                           "statusId" integer NOT NULL,
                           CONSTRAINT "pk_courses" PRIMARY KEY("courseId"),
                           CONSTRAINT "chk_courses_availability_type" CHECK("availabilityType" in ('day', 'week', 'month', 'always'))
);

CREATE TABLE "exams" (
                         "examId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         "courseId" integer NOT NULL,
                         "studentId" integer NOT NULL,
                         "answers" jsonb NOT NULL DEFAULT '[]'::jsonb,
                         "questionIds" integer[],
                         "totalQuestions" integer,
                         "correctAnswers" integer,
                         "status" varchar(255) NOT NULL DEFAULT 'in_progress',
                         "finalScore" numeric(5,2),
                         "finishedAt" timestamptz,
                         "createdAt" timestamptz NOT NULL DEFAULT now(),
                         CONSTRAINT "pk_exams" PRIMARY KEY("examId"),
                         CONSTRAINT "chk_exams_status" CHECK("status" in ('in_progress', 'passed', 'failed'))
);

CREATE INDEX "IX_FK_users_statusId_users" ON "users" (
                                                      "statusId"
    );

CREATE INDEX "IX_FK_vfsFiles_folderId_vfsFiles" ON "vfsFiles" (
                                                               "folderId"
    );

CREATE INDEX "IX_FK_vfsFiles_statusId_vfsFiles" ON "vfsFiles" (
                                                               "statusId"
    );

CREATE INDEX "IX_FK_vfsFolders_folderId_vfsFolders" ON "vfsFolders" (
                                                                     "parentFolderId"
    );

CREATE INDEX "IX_FK_vfsFolders_statusId_vfsFolders" ON "vfsFolders" (
                                                                     "statusId"
    );

CREATE UNIQUE INDEX "vfsHashes_pkey" ON "vfsHashes" (
                                                     "hash",
                                                     "namespace"
    );

CREATE INDEX "IX_vfsHashes_indexedAt" ON "vfsHashes" (
                                                      "indexedAt"
    );

CREATE UNIQUE INDEX "ux_exams_active_student_course" ON "exams" (
                                                                 "courseId",
                                                                 "studentId"
    )
    WHERE "status" = 'in_progress';

ALTER TABLE "users" ADD CONSTRAINT "FK_users_statusId" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_folderId_fkey" FOREIGN KEY ("folderId")
    REFERENCES "vfsFolders"("folderId")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_statusId_fkey" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_parentFolderId_fkey" FOREIGN KEY ("parentFolderId")
    REFERENCES "vfsFolders"("folderId")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_statusId_fkey" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "students" ADD CONSTRAINT "Ref_students_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "questions" ADD CONSTRAINT "Ref_questions_to_courses" FOREIGN KEY ("courseId")
    REFERENCES "courses"("courseId")
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "questions" ADD CONSTRAINT "Ref_questions_to_vfsFiles" FOREIGN KEY ("photoFileId")
    REFERENCES "vfsFiles"("fileId")
    ON DELETE SET NULL
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "courses" ADD CONSTRAINT "Ref_courses_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "exams" ADD CONSTRAINT "Ref_exams_to_courses" FOREIGN KEY ("courseId")
    REFERENCES "courses"("courseId")
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "exams" ADD CONSTRAINT "Ref_exams_to_students" FOREIGN KEY ("studentId")
    REFERENCES "students"("studentId")
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

